#@TYPE: Machine
#@NAME: fsimx6sx
#@SOC: i.MX6SX
#@DESCRIPTION: Machine configuration for F&S boards with i.MX6 SoloX
#@MAINTAINER: Hartmut Keller <keller@fs-net.de>

MACHINEOVERRIDES =. "mx6:mx6sx:"

require conf/machine/include/imx-base.inc
require conf/machine/include/fus-base.inc
require conf/machine/include/arm/armv7a/tune-cortexa9.inc

#UBoot
UBOOT_MACHINE = "fsimx6sx_config"
PREFERRED_VERSION_u-boot-fus:mx6sx-generic-bsp  ??= "2021.04"
UBOOT_SUFFIX:mx6sx-generic-bsp = "nb0"
UBOOT_BINARY:mx6sx-generic-bsp= "uboot.${UBOOT_SUFFIX}"

#Kernel
KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE:mx6sx-generic-bsp  = "fus/efusa9x.dtb fus/efusa9xr2.dtb  fus/picocoma9x.dtb fus/cont1.dtb fus/picocoremx6sx.dtb fus/picocoremx6sxr2.dtb fus/vand3.dtb"

#RootFS
IMAGE_FSTYPES = "ubifs ext4 wic.gz"
WKS_FILE_DEPENDS:remove:mx6sx-generic-bsp = "imx-boot"
SOC_DEFAULT_WKS_FILE:mx6sx-generic-bsp= "fus-uboot-bootpart.wks.in"
UBOOT_WIC_BINARY:mx6sx-generic-bsp = "uboot.nb0"
UBOOT_OFFSET = "2048"

# Sets the login console.
# Setting FUS_LOGIN_CONSOLE automatically opens a login at
# the tty defined in the uboot environment variable "login"
# You may also specify a login here with e.g
# SERIAL_CONSOLE = "115200 ttymxc1"
# but this will also always open a login at the linux debug console
# as it is systemd default.
SERIAL_CONSOLES = "FUS_LOGIN_CONSOLE"

# Add WIFI driver
#MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "silex-wlanbt-fs-firmware"
#MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "silex-wlanbt-fs"

IMX_DEFAULT_BSP = "nxp"
