#@TYPE: Machine
#@NAME: fsimx95
#@SOC: i.MX95
#@DESCRIPTION: Machine configuration for F&S boards with i.MX95
#@MAINTAINER: Kay Müller <mueller@fs-net.de>

MACHINEOVERRIDES =. "mx95:"

require conf/machine/include/imx-base.inc
require conf/machine/include/fus-base.inc
require conf/machine/include/arm/armv8-2a/tune-cortexa55.inc

MACHINE_FEATURES += " pci wifi bluetooth optee"
MACHINE_FEATURES += " nxpiw612-sdio nxp8997-sdio"

# Kernel
KERNEL_IMAGETYPE = "Image"
KERNEL_DEVICETREE  = "\
            F+S/fssm95s.dtb \
            F+S/fssm95s-BT070L1060CS0I1AD-A.dtb \
            F+S/picocoremx95.dtb \
            "
#KERNEL_CLASSES += "kernel-fitimage"
#KERNEL_IMAGETYPES += " fitImage "
UBOOT_LOADADDRESS = "0x90400000"
UBOOT_ENTRYPOINT = "0x90200000"
UBOOT_DTB_LOADADDRESS = "0x93000000"

#UBoot
HOSTTOOLS:append = " crc32"
UBOOT_CONFIG_BASENAME = "fsimx95"
UBOOT_CONFIG ??= "fsimx95"
UBOOT_CONFIG[fsimx95] = "${UBOOT_CONFIG_BASENAME}_defconfig"
UBOOT_MAKE_TARGET = "uboot.fs"
UBOOT_SUFFIX = "fs"
UBOOT_BINARY = "uboot.${UBOOT_SUFFIX}"

# overwrite provider to build own bootloader (required)
PREFERRED_PROVIDER_u-boot:mx95-nxp-bsp = "u-boot-fus"
PREFERRED_PROVIDER_virtual/bootloader:mx95-nxp-bsp = "${PREFERRED_PROVIDER_u-boot}"

# Set ATF platform name
ATF_PLATFORM = "imx95"

DDR_FIRMWARE_NAME = " \
    lpddr4x_imem_v202409.bin \
    lpddr4x_dmem_v202409.bin \
    lpddr4x_imem_qb_v202409.bin \
    lpddr4x_dmem_qb_v202409.bin \
    lpddr5_imem_v202409.bin \
    lpddr5_dmem_v202409.bin \
    lpddr5_imem_qb_v202409.bin \
    lpddr5_dmem_qb_v202409.bin \
"

# We have to disable SERIAL_CONSOLE due to auto-serial-console
SERIAL_CONSOLES = "115200;ttyLP0"

#RootFS
IMAGE_FSTYPES = "ext4 wic"
# set default wic file
WKS_FILE = "fus-no-uboot-bootpart.wks.in"
WKS_FILE_DEPENDS:remove = "imx-boot"
IMX_BOOT_SEEK = "32"

# Sets the login console.
# You may  specify a login here with e.g
# SERIAL_CONSOLE = "115200;ttymxc1"
# but this will also always open a login at the linux debug console
# as it is systemd default.
SERIAL_CONSOLES = "FUS_LOGIN_CONSOLE"

IMX_DEFAULT_BSP = "nxp"
