#@TYPE: Machine
#@NAME: fsimx6ul
#@SOC: i.MX6UL/i.MX6ULL
#@DESCRIPTION: Machine configuration for F&S boards with i.MX6 UltraLite and i.MX6ULL
#@MAINTAINER: Hartmut Keller <keller@fs-net.de>

MACHINEOVERRIDES =. "mx6:mx6ul:mx6ull:"

require conf/machine/include/imx-base.inc
require conf/machine/include/fus-base.inc
require conf/machine/include/arm/armv7a/tune-cortexa7.inc

#UBoot
UBOOT_MACHINE = "fsimx6ul_config"
PREFERRED_VERSION_u-boot-fus:mx6ul-generic-bsp  ??= "2021.04"
UBOOT_SUFFIX:mx6ul-generic-bsp = "nb0"
UBOOT_BINARY:mx6ul-generic-bsp = "uboot.${UBOOT_SUFFIX}"

#Kernel
KERNEL_IMAGETYPE = "zImage"
KERNEL_DEVICETREE:mx6ul-generic-bsp = "fus/efusa7ul.dtb fus/efusa7ull.dtb fus/picocom1.2.dtb fus/picocoremx6ul.dtb fus/picocoremx6ul100.dtb fus/picocoremx6ull.dtb fus/picocoremx6ull100.dtb fus/picocoma7.dtb fus/picocoma7ull.dtb"

#RootFS
IMAGE_FSTYPES = "ubifs ext4 wic.gz"
WKS_FILE_DEPENDS:remove:mx6ul-generic-bsp = "imx-boot"
SOC_DEFAULT_WKS_FILE:mx6ul-generic-bsp= "fus-uboot-bootpart.wks.in"
UBOOT_WIC_BINARY:mx6ul-generic-bsp = "uboot.nb0"
UBOOT_OFFSET = "2048"

# Sets the login console.
# Setting FUS_LOGIN_CONSOLE automatically opens a login at
# the tty defined in the uboot environment variable "login"
# You may also specify a login here with e.g
# SERIAL_CONSOLE = "115200 ttymxc1"
# but this will also always open a login at the linux debug console
# as it is systemd default.
SERIAL_CONSOLES = "FUS_LOGIN_CONSOLE"

# Add WIFI driver
#MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "silex-wlanbt-fs-firmware"
#MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS += "silex-wlanbt-fs"

IMX_DEFAULT_BSP = "nxp"
